// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_labtime;
extern lv_obj_t * ui_labDate;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_labTempMorning;
extern lv_obj_t * ui_labWeatherIcon;
extern lv_obj_t * ui_labDateDay1;
extern lv_obj_t * ui_labDateDay2;
extern lv_obj_t * ui_labDateDay3;
extern lv_obj_t * ui_labWeatherIconDay1;
extern lv_obj_t * ui_labWeatherIconDay2;
extern lv_obj_t * ui_labWeatherIconDay3;
extern lv_obj_t * ui_labTempMorningDay1;
extern lv_obj_t * ui_labTempAfternoonDay1;
extern lv_obj_t * ui_labTempEveningDay1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_labTempMorningDay2;
extern lv_obj_t * ui_labTempAfternoonDay2;
extern lv_obj_t * ui_labTempEveningDay2;
extern lv_obj_t * ui_labTempMorningDay3;
extern lv_obj_t * ui_labTempAfternoonDay3;
extern lv_obj_t * ui_labTempEveningDay3;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_labAlarmEnable;
extern lv_obj_t * ui_labAlarm;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_labCalendarEvent1;
extern lv_obj_t * ui_labCalendarEvent2;
extern lv_obj_t * ui_labCalendarEvent3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

